# Generated by Django 3.0.2 on 2020-01-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caravan_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=8)),
                ('lattitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravan_routes.Route')),
                ('quest_progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caravan_routes.RoutePoint')),
            ],
        ),
    ]
